# name: Image Upload App

# on:
#   push:
#     branches: [main]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v3

#       - name: Build and push docker image for backend
#         uses: mr-smithers-excellent/docker-build-push@v6
#         with:
#           image: hysy9255/diaryboard-aws-s3-backend
#           registry: docker.io
#           directory: ./backend
#           tags: latest
#           dockerfile: ./backend/dockerfile
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}
#         env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           AWS_BUCKET_NAME: ${{ secrets.AWS_BUCKET_NAME }}
#           DATABASE_URI: ${{ secrets.DATABASE_URI }}

#       - name: Build and push docker image for frontend
#         uses: mr-smithers-excellent/docker-build-push@v6
#         with:
#           image: hysy9255/diaryboard-aws-s3-frontend
#           registry: docker.io
#           directory: ./frontend
#           tags: latest
#           dockerfile: ./frontend/dockerfile
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

name: Our First Workflow
on: push
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Hello, GitHub Actions!'
  pwd-ls:
    name: PWD & LS
    runs-on: ubuntu-latest
    steps:
      - name: Print working directory
        run: pwd
      - name: List files
        run: ls -al
